#!/bin/fish

# A little script to restart Waybar accepts "q" or "-q"
# as arguments to make Waybar quiet

if pidof -q waybar
    kill waybar
end

switch $argv[1]
  case "q" "-q"
    waybar -l off &
  case "*"
    waybar &
end
