#!/bin/fish

# A little script to restart Waybar, accepts "q" or "-q" as arguments to make Waybar quiet

if pidof -q waybar
    kill waybar
end
if test "$argv[1]" = "q"; or test "$argv[1]" = "-q"
    waybar -l off &
    disown (jobs -p)
else
    waybar &
    disown (jobs -p)
end
