#!/usr/bin/fish


# Super+W to close the focused view
riverctl map normal Super W close

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# I really don't understand how River tags work
# Fourth tag is the same that the third one, don't know why

for i in $(seq 1 2)
    riverctl map normal Super $i set-focused-tags $i
    riverctl map normal Super+Shift $i set-view-tags $i
end
riverctl map normal Super 3 set-focused-tags 00100 
riverctl map normal Super 4 set-focused-tags 01000
riverctl map normal Super 5 set-focused-tags 10000

riverctl map normal Super+Shift 3 set-view-tags 00100
riverctl map normal Super+Shift 4 set-view-tags 01000
riverctl map normal Super+Shift 5 set-view-tags 00100

# Super+Space to toggle float
riverctl map normal Super Space toggle-float
# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode no-keys

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode no-keys

# Super+F11 to return to normal mode
riverctl map no-keys Super F11 enter-mode normal

riverctl map normal None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
riverctl map normal None XF86AudioLowerVolume  spawn 'pamixer -d 5'
riverctl map normal None XF86AudioMute         spawn 'pamixer --toggle-mute'

riverctl map normal None XF86AudioMedia spawn 'playerctl play-pause'
riverctl map normal None XF86AudioPlay  spawn 'playerctl play-pause'
riverctl map normal None XF86AudioPrev  spawn 'playerctl previous'
riverctl map normal None XF86AudioNext  spawn 'playerctl next'

riverctl map normal None XF86MonBrightnessUp   spawn 'light -A 5'
riverctl map normal None XF86MonBrightnessDown spawn 'light -U 5'

riverctl background-color 0x002b36
riverctl border-width 1
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

riverctl set-repeat 50 300

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 4 -outer-padding 4 -main-ratio 0.5 &

# Keybindings

riverctl map normal Super D spawn ~/.local/bin/launcher
riverctl map normal Super G spawn librewolf
riverctl map normal Super Return spawn alacritty
riverctl map normal Super+Shift S spawn ~/.local/bin/shot
riverctl map normal Super+Shift I spawn "light -U 10"
riverctl map normal Super+Shift O spawn "light -A 10"
riverctl map normal Super E spawn pcmanfm
riverctl map normal Super+Shift C spawn "playerctl play-pause"
riverctl map normal Super+Shift E spawn "~/.local/bin/logout-menu r"
riverctl map normal Super+Shift V spawn "playerctl next"

# Misc

riverctl keyboard-layout es
riverctl focus-follows-cursor normal
riverctl input touch-8521-21593-Weida_weida events disabled # This is for turning off my touch screen, you probably want to comment this out
riverctl xcursor-theme Vimix-cursors
wl-clip-persist -c regular &

# Autostart stuff

wbg ~/Pictures/clouds.jpg & 
polkit-gnome &
way r &
dunst &
